# Site settings
name: 周纪元
location: 四川成都
position: 金融、人力资源、管理、数据分析
# github: https://github.com/
# facebook: https://www.facebook.com/
phone: 15680075115
email: zhou@jiyuan.enail.cn

# baseurl: "/resume.io"
baseurl: https://callmechou.github.io/resume.github.io/
permalink: /:year/:month/:day/:title/

exclude: ['README.md']
source: "https://rubygems.org"
gem: 'github-pages'
# Build settings
markdown: kramdown

